apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictionserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: gcr.io/wide-journey-251423/predictionserver
        resources:
            limits:
              memory: "2000Mi"
              cpu: "2000m" 
            requests:
              memory: "2000Mi"
              cpu: "2000m"